name: "Build and populate cache"
on:
  push:
jobs:
  tests:
    strategy:
      matrix:
        nurRepo:
          - vroad
        cachixName:
          - vroad
        nixChannel:
          - nixpkgs-unstable
          - nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Install nix
      uses: cachix/install-nix-action@v13
    - name: Set nix path
      run: |
        echo "NIX_PATH=nixpkgs=$(nix eval --raw '(with import ./nix/sources.nix;${{ matrix.nixChannel }}.outPath)')" >> $GITHUB_ENV
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: ${{ matrix.cachixName }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Check evaluation
      run: |
        nix-env -f . -qa \* --meta --xml \
          --allowed-uris https://github.com \
          --option restrict-eval true \
          --option allow-import-from-derivation true \
          --drv-path --show-trace \
          -I $PWD
    - name: Build nix packages
      run: nix run nixpkgs.nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs --arg pkgs 'import <nixpkgs> {}'
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=${{ matrix.nurRepo }}"
